### ISSUE TITLE
better RegEx which finds error/warning kinds of lines

### ISSUE THREAD

**Issue by CudaText-addons** [kaste/SublimeLinter-contrib-quick-linter-js#1]
```
    regex = (
        r"^(?P<filename>.+?):(?P<line>\d+):(?P<col>\d+):\s"
        r"(?P<message>((?P<error>error:)|(?P<warning>warning:)).+)\s\[(?P<code>\w+)]"
    )
```
this way SublimeLinter can detect lines 'kinds'.

also at and, content of `?P<code>`, changed to `\w+`.

**Comment by kaste** [comment]
Reasonable.  I was very defensive here because `quick-lint-js` is very young, and thought maybe everything changes here rather quickly.  But 

```
        r"((?P<error>error:)|(?P<warning>warning:)\s)?(?P<message>.+)\s"
```

is probably better.  Because if we "detect" or parse for the `kind`, we should not also leave it in the message but *extract* it, no?

![image](https://user-images.githubusercontent.com/8558/194558193-34f594e2-cb8d-4aac-a2b6-26a12510db9f.png)

Why the `w+` though?

**Comment by kaste** [comment]
https://regex101.com/r/U8y6xs/1

**Comment by Alexey-T** [comment]
Why \w+ . To make it safer if future version appears with output 'Error line [some text here]'.

**Comment by Alexey-T** [comment]
> but extract it, no?

Ok.
